service: integrotion

provider:
  name: azure
  location: West Europe
  runtime: nodejs12
  versionFunctions: false
  prefix: integrotion

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-tree-shake
  - serverless-azure-functions

package:
  excludeDevDependencies: false
  include:
    - '**/function.json'
    - 'host.json'

functions:
  - todoistWebhook:
      handler: dist/endpoints/todoistWebhook
      events:
        - http: true
          route: todoistWebhook
          authLevel: anonymous
  - todoistQueue:
      handler: dist/endpoints/todoistQueue
      events:
        - queue: todoist
          name: itemAdded
          connection: AzureWebJobsStorage
  - setBotWebhook:
      handler: dist/endpoints/setBotWebhook
      events:
        - http: true
          route: setBotWebhook
          authLevel: anonymous
  - botWebhook:
      handler: dist/endpoints/botWebhook
      events:
        - http: true
          route: botWebhook
          authLevel: anonymous
  - ping:
      handler: dist/endpoints/ping
      events:
        - timer:
          name: timer
          schedule: '* */15 * * * *'